# Guides at https://confluence.atlassian.com/x/14UWN for more examples.

image: node:6.9.4
pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run build
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build/bin/setups/EmojiToolsSetup.exe"